### ISSUE TITLE
Add ability to delete entities

### ISSUE THREAD

**Issue by amgoodfellow** [RecCenterManagement/rec-management-frontend#63]

**Comment by EliteMasterEric** [comment]
Add handlers in success/error:
- [x] Equipment
- [x] EquipmentBundle
- [x] EquipmentReservation
- [x] Facilities
- [x] Reservations
- [x] Users

Rework the reducers
- [x] Equipment
- [x] EquipmentBundle
- [x] EquipmentReservation
- [x] Facilities
- [x] Reservations
- [x] Users

Add functioning delete button:
- [X] Equipment
- [X] EquipmentBundle
- [X] EquipmentReservation
- [X] Facilities
- [X] Reservations
- [X] Users

**Comment by EliteMasterEric** [comment]
This issue was resolved in pull request 75.
