### ISSUE TITLE
Revisit styling

### ISSUE THREAD

**Issue by ghost** [RecCenterManagement/rec-management-frontend#90]
I personally don't mind the blue, but Patel seems to not like it.

**Comment by amgoodfellow** [comment]
It's unfortunate - a selling point of our primary / secondary colors isthat they are the official colors for all UTS developed applications.

 We can check out OU-UCM's color guidelines for potential inspiration too

**Comment by ghost** [comment]
If the blue is part of the official color guidelines then we could keep it and simply mention our compliance as a feature on our poster.

**Comment by amgoodfellow** [comment]
From an internal UTS document:

![image](https://user-images.githubusercontent.com/19152201/69649088-7d9fe580-103a-11ea-9644-f859bc32fac8.png)
